### ISSUE TITLE
希望合入OpenWHU项目

### ISSUE THREAD

**Issue by Crescentm** [JinlongLi2016/AlgorithmsDesignTechniquesandAnalysis#2]
看到学长所搜集的资料，想把您的资料收集进OpenWHU项目，望批准❤
[项目地址](https://github.com/openwhu/OpenWHU)

**Comment by JinlongLi2016** [comment]
本作品采用知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议进行许可。

PS: 试卷分享牛逼 👍

**Comment by JinlongLi2016** [comment]
> 看到学长所搜集的资料，想把您的资料收集进OpenWHU项目，望批准❤
> [项目地址](https://github.com/openwhu/OpenWHU)

本作品采用知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议进行许可。
PS: 试卷分享牛逼 👍
